export default [
    {
        id: 1,
        surname: "Степанов",
        name: "Михаил",
        patronymic: "Дмитриевич",
        gender: "мужской",
        birth_date: "15.06.2005",
        group: "П11",
    },
    {
        id: 2,
        surname: "Поликарпов",
        name: "Максим",
        patronymic: "Дмитриевич",
        gender: "мужской",
        birth_date: "24.10.2005",
        group: "П11",
    },
    {
        id: 3,
        surname: "Кузнецова",
        name: "София",
        patronymic: "Глебовна",
        gender: "женский",
        birth_date: "23.10.2005",
        group: "П11",
    },
    {
        id: 4,
        surname: "Кулаков",
        name: "Григорий",
        patronymic: "Викторович",
        gender: "мужской",
        birth_date: "17.07.2005",
        group: "П11",
    },
    {
        id: 5,
        surname: "Соколов",
        name: "Даниил",
        patronymic: "Иванович",
        gender: "мужской",
        birth_date: "14.11.2005",
        group: "П12",
    },
    {
        id: 6,
        surname: "Русакова",
        name: "Екатерина",
        patronymic: "Евгеньевна",
        gender: "женский",
        birth_date: "23.11.2005",
        group: "П12",
    },
    {
        id: 7,
        surname: "Поляков",
        name: "Иван",
        patronymic: "Иванович",
        gender: "мужской",
        birth_date: "23.08.2005",
        group: "П12",
    },
    {
        id: 8,
        surname: "Максимов",
        name: "Максим",
        patronymic: "Григорьевич",
        gender: "мужской",
        birth_date: "23.12.2005",
        group: "П12",
    },
    {
        id: 9,
        surname: "Моргунова",
        name: "Алиса",
        patronymic: "Ильинична",
        gender: "женский",
        birth_date: "23.12.2005",
        group: "П13",
    },
    {
        id: 10,
        surname: "Тарасов",
        name: "Глеб",
        patronymic: "Тимурович",
        gender: "мужской",
        birth_date: "10.01.2005",
        group: "П13",
    },
    {
        id: 11,
        surname: "Орлов",
        name: "Сергей",
        patronymic: "Артёмович",
        gender: "мужской",
        birth_date: "15.01.2005",
        group: "П13",
    },
    {
        id: 12,
        surname: "Иванова",
        name: "Оливия",
        patronymic: "Денисовна",
        gender: "женский",
        birth_date: "23.01.2005",
        group: "П13",
    },
    {
        id: 13,
        surname: "Емельянов",
        name: "Георгий",
        patronymic: "Кириллович",
        gender: "мужской",
        birth_date: "05.02.2005",
        group: "П21",
    },
    {
        id: 14,
        surname: "Иванов",
        name: "Максим",
        patronymic: "Святославович",
        gender: "мужской",
        birth_date: "15.02.2005",
        group: "П21",
    },
    {
        id: 15,
        surname: "Захарова",
        name: "Мария",
        patronymic: "Платоновна",
        gender: "женский",
        birth_date: "23.02.2005",
        group: "П21",
    },
    {
        id: 16,
        surname: "Денисов",
        name: "Даниил",
        patronymic: "Андреевич",
        gender: "мужской",
        birth_date: "22.03.2005",
        group: "П21",
    },
    {
        id: 17,
        surname: "Старостин",
        name: "Никита",
        patronymic: "Степанович",
        gender: "мужской",
        birth_date: "23.03.2005",
        group: "П22",
    },
    {
        id: 18,
        surname: "Лебедева",
        name: "Амина",
        patronymic: "Алексеевна",
        gender: "женский",
        birth_date: "23.03.2005",
        group: "П22",
    },
    {
        id: 19,
        surname: "Корнилов",
        name: "Матвей",
        patronymic: "Дмитриевич",
        gender: "мужской",
        birth_date: "25.04.2005",
        group: "П22",
    },
    {
        id: 20,
        surname: "Ширяева",
        name: "Варвара",
        patronymic: "Филипповна",
        gender: "женский",
        birth_date: "23.04.2005",
        group: "П22",
    },
    {
        id: 21,
        surname: "Гончарова",
        name: "Милана",
        patronymic: "Львовна",
        gender: "женский",
        birth_date: "23.04.2005",
        group: "П23",
    },
    {
        id: 22,
        surname: "Кузнецов",
        name: "Давид",
        patronymic: "Владимирович",
        gender: "мужской",
        birth_date: "05.05.2005",
        group: "П23",
    },
    {
        id: 23,
        surname: "Романова",
        name: "Камила",
        patronymic: "Ивановна",
        gender: "женский",
        birth_date: "23.05.2005",
        group: "П23",
    },
    {
        id: 24,
        surname: "Егорова",
        name: "Ксения",
        patronymic: "Дмитриевна",
        gender: "женский",
        birth_date: "23.05.2005",
        group: "П23",
    },
    {
        id: 25,
        surname: "Беляков",
        name: "Александр",
        patronymic: "Данилович",
        gender: "мужской",
        birth_date: "07.06.2005",
        group: "П31",
    },
    {
        id: 26,
        surname: "Скворцова",
        name: "Дарья",
        patronymic: "Александровна",
        gender: "женский",
        birth_date: "23.06.2005",
        group: "П31",
    },
    {
        id: 27,
        surname: "Васильева",
        name: "Полина",
        patronymic: "Алиевна",
        gender: "женский",
        birth_date: "23.06.2005",
        group: "П31",
    },
    {
        id: 28,
        surname: "Сергеев",
        name: "Даниил",
        patronymic: "Николаевич",
        gender: "мужской",
        birth_date: "09.07.2005",
        group: "П31",
    },
    {
        id: 29,
        surname: "Григорьева",
        name: "Ульяна",
        patronymic: "Данииловна",
        gender: "женский",
        birth_date: "23.07.2005",
        group: "П32",
    },
    {
        id: 30,
        surname: "Крюкова",
        name: "Мария",
        patronymic: "Ивановна",
        gender: "женский",
        birth_date: "23.07.2005",
        group: "П32",
    },
    {
        id: 31,
        surname: "Соловьев",
        name: "Тихон",
        patronymic: "Маркович",
        gender: "мужской",
        birth_date: "18.08.2005",
        group: "П32",
    },
    {
        id: 32,
        surname: "Медведева",
        name: "Ирина",
        patronymic: "Родионовна",
        gender: "женский",
        birth_date: "23.08.2005",
        group: "П32",
    },
    {
        id: 33,
        surname: "Савина",
        name: "Яна",
        patronymic: "Тихоновна",
        gender: "женский",
        birth_date: "23.08.2005",
        group: "П33",
    },
    {
        id: 34,
        surname: "Казаков",
        name: "Артём",
        patronymic: "Михайлович",
        gender: "мужской",
        birth_date: "19.09.2005",
        group: "П33",
    },
    {
        id: 35,
        surname: "Рыжова",
        name: "Есения",
        patronymic: "Дмитриевна",
        gender: "женский",
        birth_date: "23.09.2005",
        group: "П33",
    },
    {
        id: 36,
        surname: "Михайлова",
        name: "Мария",
        patronymic: "Эминовна",
        gender: "женский",
        birth_date: "23.09.2005",
        group: "П33",
    }
]