import img1 from "../img/teacher_1.jpg"
import img2 from "../img/teacher_2.jpg"
import img3 from "../img/teacher_3.jpg"
import img4 from "../img/teacher_4.jpg"
import img5 from "../img/teacher_5.jpg"
import img6 from "../img/teacher_6.jpg"
import img7 from "../img/teacher_7.jpg"
import img8 from "../img/teacher_8.jpg"
import img9 from "../img/teacher_9.jpg"
import img10 from "../img/teacher_10.jpg"
import img11 from "../img/teacher_11.jpg"
import img12 from "../img/teacher_12.jpg"
import img13 from "../img/teacher_13.jpg"
import img14 from "../img/teacher_14.jpg"
import img15 from "../img/teacher_15.jpg"
import img16 from "../img/teacher_16.jpg"
import img17 from "../img/teacher_17.jpg"
import img18 from "../img/teacher_18.jpg"
import img19 from "../img/teacher_19.jpg"

export default [
    {
        id: 1,
        surname: "Иванов",
        name: "Иван",
        patronymic: "Иванович",
        gender: "мужской",
        birth_date: "15.06.1985",
        phone: "+71234567890",
        degree: "ассистент",
        salary: "40000р",
        cathedra: "Кафедра физической культуры",
        photo: img1,
    },
    {
        id: 2,
        surname: "Петрова",
        name: "Ольга",
        patronymic: "Владимировна",
        gender: "женский",
        birth_date: "20.09.1978",
        phone: "+72345678900",
        degree: "преподаватель",
        salary: "60000р",
        cathedra: "Кафедра педагогики и психологии",
        photo: img2,
    },
    {
        id: 3,
        surname: "Сидорова",
        name: "Елена",
        patronymic: "Петровна",
        gender: "женский",
        birth_date: "10.04.1990",
        phone: "+73456789012",
        degree: "ст. преподаватель",
        salary: "75000р",
        cathedra: "Кафедра математики и информатики",
        photo: img3,
    },
    {
        id: 4,
        surname: "Козлов",
        name: "Дмитрий",
        patronymic: "Александрович",
        gender: "мужской",
        birth_date: "25.11.1975",
        phone: "+74567890123",
        degree: "доцент",
        salary: "80000р",
        cathedra: "Кафедра лингвистики и межкультурной коммуникации",
        photo: img4,
    },
    {
        id: 5,
        surname: "Никитина",
        name: "Анастасия",
        patronymic: "Сергеевна",
        gender: "женский",
        birth_date: "05.08.1982",
        phone: " +75678901234",
        degree: "профессор",
        salary: "90000р",
        cathedra: "Кафедра математики и информатики",
        photo: img5,
    },
    {
        id: 6,
        surname: "Григорьев",
        name: "Владимир",
        patronymic: "Васильевич",
        gender: "мужской",
        birth_date: "30.03.1995",
        phone: "+76789012345",
        degree: "ассистент",
        salary: "35000р",
        cathedra: "Кафедра математики и информатики",
        photo: img6,
    },
    {
        id: 7,
        surname: "Лебедева",
        name: "Мария",
        patronymic: "Андреевна",
        gender: "женский",
        birth_date: "12.07.1988",
        phone: "+77890123456",
        degree: "преподаватель",
        salary: "55000р",
        cathedra: "Кафедра гуманитарных дисциплин",
        photo: img7,
    },
    {
        id: 8,
        surname: "Смирнов",
        name: "Алексей",
        patronymic: "Николаевич",
        gender: "мужской",
        birth_date: "18.01.1980",
        phone: "+78901234567",
        degree: "ст. преподаватель",
        salary: "70000р",
        cathedra: "Кафедра гуманитарных дисциплин",
        photo: img8,
    },
    {
        id: 9,
        surname: "Зайцева",
        name: "Екатерина",
        patronymic: "Дмитриевна",
        gender: "женский",
        birth_date: "07.09.1973",
        phone: "+79012345678",
        degree: "доцент",
        salary: "85000р",
        cathedra: "Кафедра лингвистики и межкультурной коммуникации",
        photo: img9,
    },
    {
        id: 10,
        surname: "Белов",
        name: "Игорь",
        patronymic: "Сергеевич",
        gender: "мужской",
        birth_date: "29.12.1987",
        phone: "+70123456789",
        degree: "профессор",
        salary: "95000р",
        cathedra: "Кафедра математики и информатики",
        photo: img10,
    },
    {
        id: 11,
        surname: "Морозов",
        name: "Артем",
        patronymic: "Михайлович",
        gender: "мужской",
        birth_date: "30.07.1975",
        phone: "+79102345678",
        degree: "профессор",
        salary: "80000р",
        cathedra: "Кафедра дизайна",
        photo: img11,
    },
    {
        id: 12,
        surname: "Кузнецов",
        name: "Дмитрий",
        patronymic: "Игоревич",
        gender: "мужской",
        birth_date: "17.12.1980",
        phone: "+79109876543",
        degree: "доцент",
        salary: "55000р",
        cathedra: "Кафедра математики и информатики",
        photo: img12,
    },
    {
        id: 13,
        surname: "Васильев",
        name: "Илья",
        patronymic: "Валерьевич",
        gender: "мужской",
        birth_date: "14.04.1992",
        phone: "+79172346578",
        degree: "ст. преподаватель",
        salary: "65000р",
        cathedra: "Кафедра математики и информатики",
        photo: img13,
    },
    {
        id: 14,
        surname: "Карпова",
        name: "Дарья",
        patronymic: "Сергеевна",
        gender: "женский",
        birth_date: "20.02.1980",
        phone: "+79258765432",
        degree: "профессор",
        salary: "90000р",
        cathedra: "Кафедра физической культуры",
        photo: img14,
    },
    {
        id: 15,
        surname: "Гаврилов",
        name: "Алексей",
        patronymic: "Петрович",
        gender: "мужской",
        birth_date: "06.10.1987",
        phone: "+79101234567",
        degree: "ассистент",
        salary: "38000р",
        cathedra: "Кафедра менеджмента",
        photo: img15,
    },
    {
        id: 16,
        surname: "Жукова",
        name: "Ольга",
        patronymic: "Васильевна",
        gender: "женский",
        birth_date: "29.03.1976",
        phone: "+79157654321",
        degree: "доцент",
        salary: "58000р",
        cathedra: "Кафедра математики и информатики",
        photo: img16,
    },
    {
        id: 17,
        surname: "Тимошенко",
        name: "Анатолий",
        patronymic: "Николаевич",
        gender: "мужской",
        birth_date: "12.07.1983",
        phone: "+79033456789",
        degree: "преподаватель",
        salary: "50000р",
        cathedra: "Кафедра экономики и финансов",
        photo: img17,
    },
    {
        id: 18,
        surname: "Соловьева",
        name: "Елена",
        patronymic: "Ивановна",
        gender: "женский",
        birth_date: "18.09.1993",
        phone: "+79259876543",
        degree: "ст. преподаватель",
        salary: "72000р",
        cathedra: "Кафедра математики и информатики",
        photo: img18,
    },
    {
        id: 19,
        surname: "Поляков",
        name: "Игорь",
        patronymic: "Алексеевич",
        gender: "мужской",
        birth_date: "05.11.1972",
        phone: "+79102345678",
        degree: "профессор",
        salary: "85000р",
        cathedra: "Кафедра математики и информатики",
        photo: img19,
    },
    // {
    //     id: 20,
    //     surname: "",
    //     name: "",
    //     patronymic: "",
    //     gender: "",
    //     birth_date: "",
    //     phone: "",
    //     degree: "",
    //     salary: "",
    //     cathedra: "",
    //     photo: "",
    // },
];